### ISSUE TITLE
No comment syntax configured

### ISSUE THREAD

**Issue by aspiwack** [nickel-lang/nickel-mode#12]
I'm noticing that if I call `comment-region` (generally invoked via `comment-dwim`/`M-;`), there is no comment syntax configured.

I don't have time right now to figure what invocation to add to the mode for that to happen. So just leaving an issue rather than what must be a rather straightforward PR.

**Comment by purcell** [comment]
Probably need to set `comment-start` to `"# "` and `comment-end` to `""` [here](https://github.com/nickel-lang/nickel-mode/blob/main/nickel-mode.el#L112). Reload the elisp, reapply in a nickel-mode buffer with `M-x normal-mode`. If it doesn't work, probably means that the `syntax-propertize` function needs to be extended.

**Comment by aspiwack** [comment]
Indeed, it worked like a charm. Thanks for the tip!

**Comment by purcell** [comment]
yay!
